#! /bin/bash  -xue

script_dir=$(readlink -f "$(dirname "$0")")

env  \
    AUTOMAKE_BUILD_TYPE=Debug       \
    CXXFLAGS=' -static-libgcc -static-libstdc++ -static'    \
    CFLAGS=' -static-libgcc -static-libstdc++ -static'      \
    LDFLAGS=' -static-libgcc -static-libstdc++ -static'     \
"${script_dir}/run-autoconf"  "$@"
